name: e_auth_client
description: A Flutter package for auth projects with jwtTokens .
version: 0.0.1
homepage: https://github.com/byusric/e_auth_client

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
