name: exeditec_auth_client
description: A new Flutter package project.
version: 0.0.1
homepage: https

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
